name: Deploy Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: ["docs", ".github/workflows/docs.yml"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install and Build 🔧
        run: |
          pnpm i -r
          cd tools/builder && pnpm build
          cd ../../core && pnpm build
          cd ../docs && npm run build
          cd ../
      - run: touch ./docs/out/.nojekyll # prevents github from ignoring underscore files
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/out
