name: Lint project

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths: ["playwright/**/*", "core/**/*", ".github/workflows/linter.yml"]
  push:
    branches: [main]
    paths: ["playwright/**/*", "core/**/*", ".github/workflows/linter.yml"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install
        run: pnpm i -r
      - name: Lint
        run: pnpm run lint
