name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install and Build 🔧
        run: |
          pnpm i -r
          pnpm exec playwright install --with-deps
      - name: Run Tests
        run: |
          pnpm run test
          pnpm run ct:run
