name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths: ["playwright/**/*", "core/**/*", ".github/workflows/tests.yml"]
  push:
    branches: [main]
    paths: ["playwright/**/*", "core/**/*", ".github/workflows/tests.yml"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i -r
      - name: Lint project
        run: pnpm run lint:relative
      - name: Install playwright
        run: pnpm exec playwright install --with-deps
      - name: Run Tests
        run: |
          pnpm run test
          pnpm run ct:run
